[package]
name = "xlsx2csv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine="0.24"
csv="1.3"
clap="3.0"